### ISSUE TITLE
无法启动游戏

### ISSUE THREAD

**Issue by welkinmoon** [DreamRealmCraft/malilib-forge#1]
[minecraft-exported-crash-info-2023-06-29T18-16-13.zip](https://github.com/DreamRealmCraft/malilib-forge/files/11904702/minecraft-exported-crash-info-2023-06-29T18-16-13.zip)
安装了大佬移植的masa全家桶，但是启动游戏闪退，FORGE版本47.0.19，MC版本1.20.1，错误日志发在附件内`
![安装的MOD](https://github.com/DreamRealmCraft/malilib-forge/assets/85944927/a0ef205f-0272-412a-81fb-6a12c434e53a)

**Comment by Forgot-Dream** [comment]
bug已修复，使用 https://github.com/DreamRealmCraft/malilib-forge/releases/tag/20230629 应该不会出现此问题了。

**Comment by welkinmoon** [comment]
已经可以正常启动，感谢大佬，大佬辛苦了。
